name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-wasm:
    name: build-wasm
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu-develop
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project
        run: |
          tipi . --dont-upgrade --verbose -t wasm-asmjs-cxx17 --test all

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu-develop

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project
        run: |
          tipi . --dont-upgrade --verbose -t gcc-7-cxx17 --test all
